behaviors:
  AircraftTakeOff:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 10000
environment_parameters:
  airport_difficulty:
    curriculum:
      - name: level1
        completion_criteria:
          measure: reward
          behavior: AircraftTakeOff
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.0
            max_value: 0.2
      - name: level2
        completion_criteria:
          measure: reward
          behavior: AircraftTakeOff
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.2
            max_value: 0.4
      - name: level3
        completion_criteria:
          measure: reward
          behavior: AircraftTakeOff
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.4
            max_value: 0.6
      - name: level4
        completion_criteria:
          measure: reward
          behavior: AircraftTakeOff
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.6
            max_value: 0.8
      - name: level5
        completion_criteria:
          measure: reward
          behavior: AircraftTakeOff
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 1.6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0.8
            max_value: 1.0
      - name: level6
        value:
          sampler_type: uniform
          sampler_parameters:
            min_value: 0
            max_value: 1.0